default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres  # This matches the service name
      user: dbt_user
      password: dbt_pass
      port: 5432
      dbname: dbt_db
      schema: public
      threads: 1
